### ISSUE TITLE
Error - This is my best description

### ISSUE THREAD

**Issue by darshanmukunda98** [crusifficadus/SSNBIoT#1]
$ gcc nb-iot.c 
nb-iot.c: In function ‘main’:
nb-iot.c:87:19: warning: implicit declaration of function ‘time’ [-Wimplicit-function-declaration]
  srand((unsigned) time(NULL));
                   ^~~~
/usr/bin/ld: /tmp/cce6St6X.o: in function `main':
nb-iot.c:(.text+0xb5): undefined reference to `pcg32_srandom_r'
/usr/bin/ld: nb-iot.c:(.text+0x377): undefined reference to `pcg32_boundedrand_r'
/usr/bin/ld: nb-iot.c:(.text+0x398): undefined reference to `pcg32_boundedrand_r'
/usr/bin/ld: nb-iot.c:(.text+0x3e5): undefined reference to `pcg32_boundedrand_r'
/usr/bin/ld: nb-iot.c:(.text+0x414): undefined reference to `pcg32_boundedrand_r'
/usr/bin/ld: nb-iot.c:(.text+0xa11): undefined reference to `pcg32_boundedrand_r'
collect2: error: ld returned 1 exit status

**Comment by crusifficadus** [comment]
you need to run it together with pcg-random. download it and run it with nb-iot.c (example : gcc nb-iot.c pcg-random.c). or you can use rand() function but their randomization isn't good enough for this purpose.
